# Generated by Django 5.1.1 on 2024-10-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='color',
            field=models.CharField(choices=[('red-500', 'Red'), ('orange-500', 'Orange'), ('amber-500', 'Amber'), ('yellow-500', 'Yellow'), ('lime-500', 'Lime'), ('green-500', 'Green'), ('emerald-500', 'Emerald'), ('teal-500', 'Teal'), ('cyan-500', 'Cyan'), ('light-blue-500', 'Light Blue'), ('blue-500', 'Blue'), ('indigo-500', 'Indigo'), ('violet-500', 'Violet'), ('purple-500', 'purple'), ('fuschia-500', 'Fuschia'), ('pink-500', 'Pink')], default='gray-500', max_length=20),
        ),
    ]
