# Generated by Django 5.1.1 on 2024-10-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_alter_course_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileelement',
            name='file_url',
            field=models.URLField(default=''),
        ),
    ]
