# Generated by Django 5.1.1 on 2024-10-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0007_note_dislikes_note_likes_delete_notereaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='element',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='element',
            name='note',
        ),
        migrations.RemoveField(
            model_name='fileelement',
            name='element_ptr',
        ),
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='color',
            field=models.CharField(choices=[('red-500', 'Red'), ('orange-500', 'Orange'), ('amber-500', 'Amber'), ('lime-500', 'Lime'), ('green-500', 'Green'), ('emerald-500', 'Emerald'), ('teal-500', 'Teal'), ('cyan-500', 'Cyan'), ('blue-500', 'Blue'), ('indigo-500', 'Indigo'), ('violet-500', 'Violet'), ('purple-500', 'Purple'), ('fuschia-500', 'Fuschia'), ('pink-500', 'Pink')], default='gray-500', max_length=20),
        ),
        migrations.DeleteModel(
            name='TextElement',
        ),
        migrations.DeleteModel(
            name='Element',
        ),
        migrations.DeleteModel(
            name='FileElement',
        ),
    ]
